In [1]:
import pandas as pd

df = pd.read_csv("realtor-data.zip.csv")

# Keep only needed columns
cols = ["status", "price", "bedrooms", "bathrooms", "city", "state", "sqft"]
df = df[cols]

# Remove rows with ANY missing values in those columns
df = df.dropna(subset=cols)

# Optional: remove zero or invalid values
df = df[(df["price"] > 0) & (df["sqft"] > 0)]

df.to_csv("cleaned_data.csv", index=False)

In [3]:
df.isnull().sum()

status       0
price        0
bedrooms     0
bathrooms    0
city         0
state        0
sqft         0
dtype: int64

In [5]:
df = df[
    (df["price"] > 10000) &   # remove super low junk listings
    (df["sqft"] > 200) &      # remove unrealistic sizes
    (df["bedrooms"] > 0) &
    (df["bathrooms"] > 0)
]

In [7]:
df["price_per_sqft"] = df["price"] / df["sqft"]

In [9]:
df.to_csv("final_real_estate_clean.csv", index=False)

In [11]:
import pandas as pd
import sqlite3

In [13]:
df = pd.read_csv("cleaned_data.csv")
df.head()

     status      price  bedrooms  bathrooms        city         state    sqft
0  for_sale   365000.0       2.0        2.0  Aaronsburg  Pennsylvania  1560.0
1  for_sale   139999.0       4.0        2.0  Aaronsburg  Pennsylvania  2128.0
2  for_sale    14500.0       1.0        1.0   Abbeville       Alabama   700.0
3  for_sale  1250000.0       1.0        1.0   Abbeville     Louisiana  2000.0
4  for_sale    34000.0       2.0        1.0   Abbeville       Alabama   648.0

In [17]:
df.columns

Index(['status', 'price', 'bedrooms', 'bathrooms', 'city', 'state', 'sqft'], dtype='object')

In [19]:
conn = sqlite3.connect("real_estate.db")

In [21]:
df.to_sql("real_estate", conn, if_exists="replace", index=False)

655129

In [23]:
query = "SELECT * FROM real_estate LIMIT 5"
pd.read_sql(query, conn)

     status      price  bedrooms  bathrooms        city         state    sqft
0  for_sale   365000.0       2.0        2.0  Aaronsburg  Pennsylvania  1560.0
1  for_sale   139999.0       4.0        2.0  Aaronsburg  Pennsylvania  2128.0
2  for_sale    14500.0       1.0        1.0   Abbeville       Alabama   700.0
3  for_sale  1250000.0       1.0        1.0   Abbeville     Louisiana  2000.0
4  for_sale    34000.0       2.0        1.0   Abbeville       Alabama   648.0

In [25]:
#states which have the highest average house price
query = """
SELECT state, ROUND(AVG(price), 2) AS avg_price
FROM real_estate
GROUP BY state
ORDER BY avg_price DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

                  state     avg_price
0            California  1.075242e+09
1        Virgin Islands  1.608523e+06
2              New York  1.257103e+06
3         Massachusetts  1.082306e+06
4               Montana  1.039465e+06
5  District of Columbia  9.338567e+05
6                 Idaho  8.979062e+05
7               Florida  7.659815e+05
8           Connecticut  7.149623e+05
9              Colorado  6.335143e+05

In [27]:
#cities with highest average price
query = """
SELECT city, ROUND(AVG(price), 2) AS avg_price
FROM real_estate
GROUP BY city
ORDER BY avg_price DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

                   city     avg_price
0         International  2.147484e+09
1           Bolingbroke  4.525000e+07
2                 Campo  4.500000e+07
3            Golden Oak  1.638500e+07
4            Sagaponack  1.414687e+07
5          Golden Beach  1.331667e+07
6             Mill Neck  1.274975e+07
7           Gulf Stream  1.211675e+07
8            Waterfront  1.200000e+07
9  Jupiter Inlet Colony  1.172880e+07

In [29]:
#Average price by number of bedrooms
query = """
SELECT bedrooms, ROUND(AVG(price), 2) AS avg_price
FROM real_estate
GROUP BY bedrooms
ORDER BY bedrooms;
"""
pd.read_sql(query, conn)

    bedrooms    avg_price
0        1.0    369946.67
1        2.0    385958.09
2        3.0    410753.04
3        4.0    616142.61
4        5.0   1039154.71
..       ...          ...
67      93.0  15200000.00
68      99.0   7800000.00
69     100.0   3000000.00
70     102.0   1499000.00
71     190.0    189000.00

[72 rows x 2 columns]

In [31]:
import pandas as pd
import sqlite3

In [33]:
df = pd.read_csv("cleaned_data.csv")

In [35]:
conn = sqlite3.connect("real_estate.db")

In [39]:
query = "SELECT * FROM real_estate LIMIT 5"
pd.read_sql(query, conn)

     status      price  bedrooms  bathrooms        city         state    sqft
0  for_sale   365000.0       2.0        2.0  Aaronsburg  Pennsylvania  1560.0
1  for_sale   139999.0       4.0        2.0  Aaronsburg  Pennsylvania  2128.0
2  for_sale    14500.0       1.0        1.0   Abbeville       Alabama   700.0
3  for_sale  1250000.0       1.0        1.0   Abbeville     Louisiana  2000.0
4  for_sale    34000.0       2.0        1.0   Abbeville       Alabama   648.0

In [41]:
#Most expensive states
query = """
SELECT state, ROUND(AVG(price), 2) AS avg_price
FROM real_estate
GROUP BY state
ORDER BY avg_price DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

                  state     avg_price
0            California  1.075242e+09
1        Virgin Islands  1.608523e+06
2              New York  1.257103e+06
3         Massachusetts  1.082306e+06
4               Montana  1.039465e+06
5  District of Columbia  9.338567e+05
6                 Idaho  8.979062e+05
7               Florida  7.659815e+05
8           Connecticut  7.149623e+05
9              Colorado  6.335143e+05

In [43]:
query = """
SELECT city, ROUND(AVG(price), 2) AS avg_price
FROM real_estate
GROUP BY city
ORDER BY avg_price DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

                   city     avg_price
0         International  2.147484e+09
1           Bolingbroke  4.525000e+07
2                 Campo  4.500000e+07
3            Golden Oak  1.638500e+07
4            Sagaponack  1.414687e+07
5          Golden Beach  1.331667e+07
6             Mill Neck  1.274975e+07
7           Gulf Stream  1.211675e+07
8            Waterfront  1.200000e+07
9  Jupiter Inlet Colony  1.172880e+07

In [45]:
#prices vs bedroom
query = """
SELECT bedrooms, ROUND(AVG(price), 2) AS avg_price
FROM real_estate
GROUP BY bedrooms
ORDER BY bedrooms;
"""
pd.read_sql(query, conn)

    bedrooms    avg_price
0        1.0    369946.67
1        2.0    385958.09
2        3.0    410753.04
3        4.0    616142.61
4        5.0   1039154.71
..       ...          ...
67      93.0  15200000.00
68      99.0   7800000.00
69     100.0   3000000.00
70     102.0   1499000.00
71     190.0    189000.00

[72 rows x 2 columns]

In [47]:
#price vs size
query = """
SELECT 
    ROUND(AVG(sqft), 2) AS avg_sqft,
    ROUND(AVG(price), 2) AS avg_price
FROM real_estate;
"""
pd.read_sql(query, conn)

   avg_sqft  avg_price
0    2100.2  557871.77

In [49]:
#price per sq ft
query = """
SELECT city,
       ROUND(AVG(price / sqft), 2) AS price_per_sqft
FROM real_estate
WHERE sqft > 0
GROUP BY city
ORDER BY price_per_sqft DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

                   city  price_per_sqft
0         International      2426535.14
1              Parmelee         7628.75
2                 Campo         6428.57
3             Helmville         4977.61
4            Wise River         4623.57
5               Cohagen         3841.54
6           Bolingbroke         3351.85
7              Gulliver         3080.76
8        Thompson Ridge         2882.46
9  Jupiter Inlet Colony         2746.66

In [51]:
#Only “for_sale” properties
query = """
SELECT status, COUNT(*) as total
FROM real_estate
GROUP BY status;
"""
pd.read_sql(query, conn)

     status   total
0  for_sale  655129